<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get( 'Magento\Customer\Model\Session' );
if ( $block->getLinks() && $customerSession->isLoggedIn() ) {
?>
<div id='top-links-container' data-mage-init='{"dropdownDialog":{
                "appendTo":"div.header-account-links-wrapper",
                "triggerTarget":"a#header-account-links-label",
                "timeout": "2000",
                "closeOnMouseLeave": false,
                "closeOnEscape": true,
                "triggerClass":"active",
                "parentClass":"active",
                "buttons":[]}}'>
    <ul id='top-links' <?php echo ($block->hasCssClass() ? ' class="' . $block->escapeHtml(
                $block->getCssClass()
            ) . '"' : '');?> >
<?php
    foreach ($block->getLinks() as $link) {
        echo $block->renderLink($link);
    }
?>
    </ul>
</div>
<?php
}
